//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class Candidate
    {
        public Candidate()
        {}        
        
        public int CandidateId { get; set; }
       
        public string Name { get; set; }
        
        public string Address { get; set; }
      
        public Nullable<int> CountryId { get; set; }
       
        public Nullable<int> StateId { get; set; }
       
        public Nullable<long> PhoneNumber { get; set; }
        
        public string Email { get; set; }       
       
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        
        public bool MaritalStatus { get; set; }
       
        public string Gender { get; set; }
      
    }
}
