//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetProject.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class State
    {
        public State()
        {            
        }
    
        public int StateId { get; set; }        
        public string Name { get; set; }
        public Nullable<int> CountryId { get; set; }   
       
    }
}
